rustgd/rhusics

- Cargo.toml
- src/ecs/physics/systems/linear_impulse.rs
- src/lib.rs
- src/physics/simple.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/37)
> Updating shrev to newest release

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/39)
> Update TODO with topics from discussion on Gitter.

- examples/basic2d.rs
- examples/basic3d.rs
- examples/spatial3d.rs
- src/collide/mod.rs
- src/collide/narrow.rs
- src/collide/prelude2d.rs
- src/collide/prelude3d.rs
- src/ecs/collide/prelude2d.rs
- src/ecs/collide/prelude3d.rs
- src/ecs/collide/resources.rs
- src/ecs/collide/systems/basic.rs
- src/ecs/collide/systems/spatial_collision.rs
- src/ecs/collide/systems/spatial_sort.rs
- src/ecs/physics/prelude2d.rs
- src/ecs/physics/prelude3d.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/38)
> feat: Making contact generation optional based on shape types

- Cargo.toml
- src/ecs/physics/systems/linear_impulse.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/42)
> fix: Updating shrev to 0.8

- src/physics/volumes.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/48)
> fix: Fixing volume calculation for new primitives in collision

- examples/spatial2d.rs
- examples/spatial3d.rs
- src/ecs/physics/prelude2d.rs
- src/ecs/physics/prelude3d.rs
- src/ecs/physics/systems/current_frame.rs
- src/ecs/physics/systems/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/52)
> fix: Rename system to be more descriptive

- README.md
- rustfmt.toml
- src/collide/mod.rs
- src/collide/narrow.rs
- src/collide/prelude2d.rs
- src/collide/prelude3d.rs
- src/ecs/collide/prelude2d.rs
- src/ecs/collide/prelude3d.rs
- src/ecs/collide/systems/basic.rs
- src/ecs/collide/systems/spatial_collision.rs
- src/ecs/physics/prelude2d.rs
- src/ecs/physics/prelude3d.rs
- src/ecs/physics/resources.rs
- src/ecs/physics/systems/contact_resolution.rs
- src/ecs/physics/systems/current_frame.rs
- src/ecs/resources.rs
- src/physics/force.rs
- src/physics/prelude2d.rs
- src/physics/prelude3d.rs
- src/physics/velocity.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/53)
> fix: Adding documentation and utility functions for world register

- Cargo.toml
- src/collide/mod.rs
- src/ecs/physics/resources.rs
- src/lib.rs
- src/physics/force.rs
- src/physics/mass.rs
- src/physics/mod.rs
- src/physics/velocity.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/54)
> feat: Add serde support for common components

- .travis.yml
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/55)
> Updating version and dependencies before release

- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/56)
> fix: Upgrade to cgmath 0.16

- src/collide/broad.rs
- src/collide/mod.rs
- src/collide/narrow.rs
- src/ecs/collide/resources.rs
- src/ecs/collide/systems/basic.rs
- src/ecs/collide/systems/spatial_collision.rs
- src/ecs/resources.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhuagh/rhusics/57)
> fix: Move collision code into core and make it abstract over storage

- README.md
- bors.toml
- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/59)
> fix: Update metadata after organisation move

- rhusics-core/Cargo.toml
- rhusics-core/src/collide/narrow.rs
- rhusics-core/src/physics/volumes.rs
- rhusics-ecs/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/61)
> fix: Update to new collision

- rhusics-core/src/collide/mod.rs
- rhusics-core/src/collide/narrow.rs
- rhusics-core/src/collide2d.rs
- rhusics-core/src/collide3d.rs
- rhusics-core/src/lib.rs
- rhusics-core/src/physics/force.rs
- rhusics-core/src/physics/mass.rs
- rhusics-core/src/physics/resolution.rs
- rhusics-core/src/physics/volumes.rs
- rhusics-ecs/src/collide/systems/basic.rs
- rhusics-ecs/src/collide/systems/spatial_collision.rs
- rhusics-ecs/src/collide/systems/spatial_sort.rs
- rhusics-ecs/src/collide2d.rs
- rhusics-ecs/src/collide3d.rs
- rhusics-ecs/src/lib.rs
- rhusics-ecs/src/physics/systems/contact_resolution.rs
BREAKING CHANGE: Some functions have changed signatures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/63)
> fix: Make crate more idiomatic, using clippy.

- rhusics-core/src/body_pose.rs
- rhusics-core/src/lib.rs
- rhusics-core/src/physics/force.rs
- rhusics-core/src/physics/resolution.rs
- rhusics-core/src/physics/simple.rs
- rhusics-core/src/physics/velocity.rs
- rhusics-ecs/examples/basic2d.rs
- rhusics-ecs/examples/basic3d.rs
- rhusics-ecs/examples/spatial2d.rs
- rhusics-ecs/examples/spatial3d.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-ecs/src/physics/systems/contact_resolution.rs
- rhusics-ecs/src/physics/systems/current_frame.rs
- rhusics-ecs/src/physics/systems/next_frame.rs
- rhusics-ecs/src/physics2d.rs
- rhusics-ecs/src/physics3d.rs
- rhusics-ecs/src/resources.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/64)
> refactor: Make all core code abstract over transform implementation, using the Pose trait

- rhusics-ecs/Cargo.toml
- rhusics-ecs/src/physics/resources.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/65)
> fix: Static bodies should not have NextFrame for the pose

- rhusics-core/src/body_pose.rs
- rhusics-core/src/physics/resolution.rs
- rhusics-core/src/physics/simple.rs
- rhusics-core/src/physics/velocity.rs
- rhusics-transform/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/67)
> fix: Pose needs to return non-references, because it's not guaranteed the implementor have the correct types stored internally

- rhusics-core/src/lib.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-ecs/src/physics/systems/next_frame.rs
- rhusics-ecs/src/physics2d.rs
- rhusics-ecs/src/physics3d.rs
- rhusics-transform/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/69)
> feat: Abstract the time resource, to make it pluggable

- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
- rhusics-ecs/src/collide/systems/spatial_collision.rs
- rhusics-ecs/src/collide/systems/spatial_sort.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-ecs/src/physics/systems/contact_resolution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/70)
> refactor: Updating to new specs version

- rhusics-transform/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/71)
> feat: Implement Pose for cgmath::Decomposed

- CHANGELOG.md
- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
- rhusics-transform/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/73)
> Updating versions for release

- rhusics-core/Cargo.toml
- rhusics-core/src/collide/narrow.rs
- rhusics-core/src/physics/mass.rs
- rhusics-ecs/Cargo.toml
- rhusics-ecs/src/lib.rs
- rhusics-ecs/src/physics/mod.rs
- rhusics-ecs/src/physics/setup.rs
- rhusics-ecs/src/physics/systems/next_frame.rs
- rhusics-ecs/src/physics2d.rs
- rhusics-ecs/src/physics3d.rs
- rhusics-transform/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/75)
> feat: Add system graph setup utility functions

- CHANGELOG.md
- rhusics-core/Cargo.toml
- rhusics-core/src/body_pose.rs
- rhusics-core/src/collide/mod.rs
- rhusics-core/src/lib.rs
- rhusics-core/src/physics/force.rs
- rhusics-core/src/physics/mass.rs
- rhusics-core/src/physics/mod.rs
- rhusics-core/src/physics/velocity.rs
- rhusics-core/src/physics/volumes.rs
- rhusics-ecs/Cargo.toml
- rhusics-ecs/src/lib.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-transform/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/77)
> refactor: Rename eders to serde (feature)

- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
- rhusics-ecs/src/lib.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-ecs/src/physics/systems/contact_resolution.rs
- rhusics-transform/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/78)
> fix: Update dependencies

- CHANGELOG.md
- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/79)
> Update versions for release

- rhusics-core/src/physics/mass.rs
- rhusics-core/src/physics/mod.rs
^
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/86)
> Added missing derive Clone

- rhusics-core/Cargo.toml
- rhusics-ecs/Cargo.toml
- rhusics-transform/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/88)
> Update versions before relase

- rhusics-core/Cargo.toml
- rhusics-core/src/collide/mod.rs
- rhusics-core/src/collide/narrow.rs
- rhusics-core/src/lib.rs
- rhusics-ecs/Cargo.toml
- rhusics-ecs/examples/basic2d.rs
- rhusics-ecs/examples/basic3d.rs
- rhusics-ecs/examples/spatial2d.rs
- rhusics-ecs/examples/spatial3d.rs
- rhusics-ecs/src/collide/systems/spatial_collision.rs
- rhusics-ecs/src/collide/systems/spatial_sort.rs
- rhusics-ecs/src/lib.rs
- rhusics-ecs/src/physics/resources.rs
- rhusics-ecs/src/physics/setup.rs
- rhusics-ecs/src/physics/systems/next_frame.rs
- rustfmt.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/rhusics/89)
>  refactor: Update specs to 0.14
